### ISSUE TITLE
suggestion: badge position

### ISSUE THREAD

**Issue by 14skywalker** [xabre/xamarin-forms-tab-badge#20]
By default the badge is lifted from the baseline. We would like to be able to position the badge at the baseline.

**Comment by xabre** [comment]
can you explain this with a simple drawing? if i'm getting this right you want to align the badge text with the tab text .... this will not work in ios, is only possible in android

**Comment by 14skywalker** [comment]
Thanks for the response. Indeed only for android:

<img width="358" alt="schermafbeelding 2017-06-30 om 13 08 58" src="https://user-images.githubusercontent.com/701186/27733240-5a04c49c-5d95-11e7-9525-fd87e0120beb.png">

**Comment by xabre** [comment]
TopLeft, TopRight, BottomLeft, BottomRight and Center available starting with v1.2.0. 

- [ ] TopCenter, BottomCenter, LeftCenter, RightCenter will be part of the next release.
