### ISSUE TITLE
UITabBarItem setBadgeTextAttributes:forState:]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by pboisso** [xabre/xamarin-forms-tab-badge#24]
Hi there,

We get error on iOS 9 for text attribute.  We saw documentation that this was not supported, but were not expecting the app to crash.  

How would you recommend to handle iOS < 10 bindings?

Thanks.

Patrice

**Comment by pboisso** [comment]
Reverted back to 1.0.1 and now it's working fine.  Definitely an issue with latest version.  Thanks.

**Comment by xabre** [comment]
- [ ] Add selector check for ios < 10

**Comment by xabre** [comment]
Should be fixed with the 1.1.1 release. :)

**Comment by pboisso** [comment]
Awesome, thanks so much ! Great plugin by the way !
