### ISSUE TITLE
why got 150 warnings....

### ISSUE THREAD

**Issue by Pool4Sky** [xabre/xamarin-forms-tab-badge#27]
I used this plugin for my project, and got 150+ following kind of warnings...

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2,2): Warning XA0106: Skipping JumpinMobile.Droid.Resource.Attribute.mediaRouteControllerSecondaryTextStyle. Please check that your Nuget Package versions are compatible. (XA0106) (JumpinMobile.Droid)
...

**Comment by xabre** [comment]
What xamarin forms version are you using? Without the plugin do you still get the warnings? Thes seems to be some warnings caused by the android support libraries

**Comment by xabre** [comment]
Try the 1.3.0-pre release. I updated the Android Support libs to the latest stable. Maybe this will get rid of the warnings. I'm guessing they are caused by version missmatches

**Comment by xabre** [comment]
Please reopen if still an issue. :)
