### ISSUE TITLE
Binding: 'Page3TabBadge' property not found on 'MyProject.PageViewModels.Page3ViewModel', target property: 'MyProject.Pages.Page3.BadgeText'

### ISSUE THREAD

**Issue by iforlife** [xabre/xamarin-forms-tab-badge#28]
Hi,
first of all very nice plugin. There is a problem on Android though.

My scenario is as follows(the names are for example purposes):
- MainPage = NavigationPage(RootTabbedPage)
- RootTabbedPage is bound to its own RootTabPageViewModel which contains the properties the badges are bound to
- Inside the tabbed page are 4 pages - each one having their own ViewModels
- when the app starts all is ok - badges are set
- when I change a tab the badges disappear and the message from the title is shown

 it's like the badges are bound to the BindingContext of the CurrentPage, not of the RootTabbedPage.

On iOS all is good. The scenario there is:
- MainPage = RootTabbedPage + RootTabPageViewModel
- each tab is navi page with contect page + view model inside

**Comment by xabre** [comment]
I'm not sure I understand it completely. But if you set a different BindingContext on each page, then the tab badges will be bound to those BindingContexts. Would be cool if you had like a minimim reproduceable sample :P?
