### ISSUE TITLE
Some part of the previous badge is left when you set the badge to a shorter string

### ISSUE THREAD

**Issue by iforlife** [xabre/xamarin-forms-tab-badge#29]
set the badge to 1232, then set the same badge to 1

**Comment by iforlife** [comment]
<img width="72" alt="screen shot 2017-08-08 at 11 38 18" src="https://user-images.githubusercontent.com/11709259/29063349-19964964-7c2e-11e7-9d9f-8f020ff24793.png">

**Comment by xabre** [comment]
I'm assuming this is just android

**Comment by xabre** [comment]
Hi @iforlife 
... does not seem to happen on my android 7 device. What version of android & plugin are you using? Can you describe your scenario a bit more in detail?
