### ISSUE TITLE
It is not hidden badge (only iOS, empty val )

### ISSUE THREAD

**Issue by Tak1wa** [xabre/xamarin-forms-tab-badge#3]
If you tried to hide the badge in the 'empty value' in the iOS, empty badge is displayed. On the other hand, it is hidden in Android.

**Comment by GalFriD** [comment]
try put null and not string.empty

**Comment by xabre** [comment]
yes, this might be because of the default behaviour on ios ...

**Comment by Tak1wa** [comment]
Thanks for support!!!
