### ISSUE TITLE
Put on the navbar

### ISSUE THREAD

**Issue by angelSwp** [xabre/xamarin-forms-tab-badge#30]
Is it possible to put it on navbar?

**Comment by xabre** [comment]
could you elaborate a bit?

**Comment by xabre** [comment]
@angelSwp Maybe give me a screenshot with a drawing of what you mean? How would this look like on the supported platforms?

**Comment by angelSwp** [comment]
I need to show badge count for toolbar icon in my project both iOS & android something looks like this

[](url)https://us.v-cdn.net/5019960/uploads/editor/jj/y8dirbu5a5id.png

**Comment by xabre** [comment]
Interesting idea :) added it to the backlog

**Comment by ojuniour** [comment]
> Interesting idea :) added it to the backlog

Any updates on the feature?

**Comment by IoTFier** [comment]
Hi xabre, I think even for this future my request of having an independent badge control pluggable to any XAML view still applies. For this needs the TitleView feature of the XF 3.2 can be used by anyone while using your badge control combined with any other XF View to deliver badge in the navbar.

Thoughts?

**Comment by xabre** [comment]
v2.2.0 includes a generic badge view for XF
