### ISSUE TITLE
Support .NET standard

### ISSUE THREAD

**Issue by xabre** [xabre/xamarin-forms-tab-badge#32]
Get ready for a 2.0 release targetting .NET Standard.

- [x] updated pcl to .net standard
- [x] update nuspec
- [x] test install

**Comment by hbraasch** [comment]
Splendid. Thanks. I think it will solve my current problem:
Skipping XXXXXXXXX.Droid.Resource.Drawable.avd_show_password_1. Please check that your Nuget Package versions are compatible

**Comment by CamelCaseMaster** [comment]
is .NET Standard 2.0 supported?

**Comment by xabre** [comment]
It is now in the 2.0.0-pre release

**Comment by xabre** [comment]
Released 2.0.0
