### ISSUE TITLE
Update to XamarinForms 2.4.* -stable when released in Q3

### ISSUE THREAD

**Issue by xabre** [xabre/xamarin-forms-tab-badge#33]

**Comment by Eiskaltereistee** [comment]
When will something happen here? I need this Plugin for Xamarin Forms 2.3.4.

After installation I got over 400 Warning and 5 Errors:
`/Volumes/Macintosh HD/Visual Studio/Xamarin/zajadacz/Droid/obj/Debug/android/src/mono/android/support/v4/app/SharedElementCallback_OnSharedElementsReadyListenerImplementor.java(47,47): Error:  error: cannot find symbol
		android.support.v4.app.SharedElementCallback.OnSharedElementsReadyListener
  symbol:   class OnSharedElementsReadyListener
  location: class SharedElementCallback
 (zajadacz.Droid) javac`

Thank you!

**Comment by xabre** [comment]
Released with 1.3.0
