### ISSUE TITLE
getting an exception in ios

### ISSUE THREAD

**Issue by GalFriD** [xabre/xamarin-forms-tab-badge#4]
System.MissingMethodException: Method 'UITabBarItem.set_BadgeColor' not found.

getting this exception when trying to run this on IOS
(on android its working fine.)

have any ideas?

Thanx

**Comment by xabre** [comment]
This look like a linker issue. You might need to update your linker please include file. 

add these lines to you LinkerPleaseInclude.cs
```
public void Include(UITabBarItem item)
        {
            item.BadgeColor = UIColor.Red;
        }
```

**Comment by GalFriD** [comment]
i think it was the problem
but after i update it I cant check it on my mac because it says the its not update but i update my mac as well and my xamarin there is up to date
have any idea?

**Comment by xabre** [comment]
Is this still an issue?
