### ISSUE TITLE
System.TypeLoadException: Could not resolve the signature of a virtual method

### ISSUE THREAD

**Issue by alexOffice** [xabre/xamarin-forms-tab-badge#42]
download the source code from github yesterday.
And run the Plugin.Badge.Samle.Droid project, get the error.

01-09 12:36:20.074 I/MonoDroid(26905):   at Android.Views.ViewGroup.GetChildAt (System.Int32 index) [0x00036] in <d855bac285f44dda8a0d8510b679b1e2>:0 
01-09 12:36:20.074 I/MonoDroid(26905):   at Plugin.Badge.Droid.ViewExtensions.FindChildOfType[T] (Android.Views.ViewGroup parent) [0x0003a] in D:\xamarin-forms-tab-badge\Source\Plugin.Badge.Droid\ViewExtensions.cs:17 

![typeloadexception](https://user-images.githubusercontent.com/13270065/34705150-40db22e0-f539-11e7-9d17-69472aa44c6a.png)

**Comment by xabre** [comment]
What version of Xamarin.Android and Android SDK do you have installed?

**Comment by xabre** [comment]
I'm guessing this could also be linker issue... GetChildAt might have been removed by Linking the sdk. 
@alexOffice Is this still an issue?

**Comment by xabre** [comment]
No answer for a couple of months...closed.
