### ISSUE TITLE
Badge is not showing.

### ISSUE THREAD

**Issue by Srusti-Thakkar** [xabre/xamarin-forms-tab-badge#47]
Hi. Thanks for making this plugin. I am using your plugin in my Application, somehow it doesn't display on android. I have used bottom navigation bar plugin for display tabbar at bottom (i .e. [this](https://github.com/NAXAM/bottomtabbedpage-xamarin-forms)). I am using following code.

This is my tabbar page code.

`<naxam:BottomTabbedPage xmlns="http://xamarin.com/schemas/2014/forms"
            xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
            xmlns:views="clr-namespace:Graysons.Views"
                        xmlns:plugin="clr-namespace:Plugin.Badge.Abstractions;assembly=Plugin.Badge.Abstractions" 
            x:Class="Graysons.Views.MainPage" xmlns:naxam="clr-namespace:Naxam.Controls.Forms;assembly=Naxam.Controls.Forms">
    <TabbedPage.Children>
        <views:AddLocationPage/>        
        <views:MenuPage/>
        <views:PromoPage/>
    </TabbedPage.Children>
</naxam:BottomTabbedPage>`

Now I have separate content page and it's code is : 

`<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="Graysons.Views.MenuPage" 
             xmlns:local="clr-namespace:Graysons.Customs"
             xmlns:cc="clr-namespace:Graysons.Controls"
             xmlns:vm="clr-namespace:Graysons.ViewModels"  
             xmlns:convertors="clr-namespace:Graysons.Convertors"
             xmlns:controls="clr-namespace:CarouselView.FormsPlugin.Abstractions;assembly=CarouselView.FormsPlugin.Abstractions"
             xmlns:resources="clr-namespace:Graysons.StringResources"  
             xmlns:plugin="clr-namespace:Plugin.Badge.Abstractions;assembly=Plugin.Badge.Abstractions" 
             Title="Menus" Icon="ic_menus.png" plugin:TabBadge.BadgeText="1"
             Style="{StaticResource CustomTopBar}">
    <ContentPage.Padding>
        <OnPlatform x:TypeArguments="Thickness">
            <On Platform="Android">0</On>
            <On Platform="iOS">0,20,0,0</On>
        </OnPlatform>
    </ContentPage.Padding>
    <ContentPage.Content>
        <StackLayout BackgroundColor="#F5F5F5">
...........................................................................
</StackLayout>
<ContentPage.Content>
</ContentPage>` 

How can I solve this. The issue is because of that plugin only. Without use of that plugin I can see the badge.

**Comment by xabre** [comment]
Same as #48
