### ISSUE TITLE
[UWP] Namespace Plugin.Badge.UWP not accessible.

### ISSUE THREAD

**Issue by themultiplexer** [xabre/xamarin-forms-tab-badge#49]
Version: 2.0.0
UWP Version: Fall Creators Update
Visual Studio: 2017 15.7.3

I installed Plugin.Badge using the NuGet GUI to the PCL, iOS, Android and UWP-Project.

On Android and iOS everything works flawlessly, but I can't even export the renderer in the Assembly.cs of the UWP Project. The namespace Plugin.Badge.UWP is not even visible and so **BadgeTabbedRenderer** is not recognized.

![image](https://user-images.githubusercontent.com/22082747/41284553-eb8983ca-6e39-11e8-8ee2-d97ecca527fd.png)

What am I doing wrong?

**Comment by LeroyDL** [comment]
I've got the same problem

**Comment by xabre** [comment]
Seem to have a nuget packaging miss-configuration and the UWP.dll is not added. Need to figure out what's wrong...

**Comment by chrisgate** [comment]
How is this miss-configuration.............thanks for ur good work..


cheers

**Comment by xabre** [comment]
https://www.nuget.org/packages/Plugin.Badge/2.1.0-pre.2
Should fix this issue. Give it a try
