### ISSUE TITLE
Badge not working on Xamarin Forms 3.1 (Android only)

### ISSUE THREAD

**Issue by nicolasteitelbaum** [xabre/xamarin-forms-tab-badge#51]
Updated to Xamarin Forms 3.1 and set the tabbar to be at the bottom just like on iOS. Badge is not working for Android, iOS works just fine.

**Comment by rysbilinski** [comment]
any workaround for this guys? seeing the same issue

**Comment by reense** [comment]
Same issue!

**Comment by azucchitmg** [comment]
@rysbilinski - I have not found a workaround for the issue (yet).  It looks like this issue is related to #48 so I'm not sure if we're better off discussing this request there instead?

**Comment by henryyue2010** [comment]
need solution of the issue, any one can help?

**Comment by xabre** [comment]
Sure, it's on my roadmap, will get to it as soon as possible. Hopefully towards the end of the week.

**Comment by IoTFier** [comment]
Hi @xabre, thank you for your response.

I will be waiting and looking forward to your release. 
I am open to help you in testing / validating your changes if that would help you.

Request - 1> will you please also have a check with XF 3.2 pre2 ? 2> Can we use this badge outside of Tabbed pages independently in any other views e.g. list views item template , labels etc? 

Thanks.

**Comment by reense** [comment]
@xabre  Great to hear! Im looking forward to it.

**Comment by xabre** [comment]
Pre-release with XF 3.1 android bottom tab placement suport is out: 

https://www.nuget.org/packages/Plugin.Badge/2.1.0-pre.2

Please give it a try and let me know if you spot some problems. 

PS: you can use the `BadgeMargin` property to fine tune the position.

**Comment by xabre** [comment]
@IoTFier Interesting proposal ... will think about it

**Comment by reense** [comment]
Thank You sir! I Will try the prerelease tomorrow. Will post back if there are any issues. Thanks again!

**Comment by xabre** [comment]
Please use #48 for further feedback, this is a duplicate thread :)
