### ISSUE TITLE
Setting of the BadgePosition doesn't work with Xamarin Form 3.1+

### ISSUE THREAD

**Issue by IoTFier** [xabre/xamarin-forms-tab-badge#52]
Hi @xabre ,

I am using XF 3.1. 

Setting up the Badgeposition as one of the enum values defined (https://github.com/xabre/xamarin-forms-tab-badge#badge-position) doesn't have any effect on the position of the Badge when rendered on iOS (11.4). 
With XF 3.1, I have already reported in another bug that this badge plugin is crashing my Android version of the App.

Your help will be appreciated.

Thanks

**Comment by xabre** [comment]
The badge position property is not yet supported for iOS as there is no direct way to do this.

See limitations: 
https://github.com/xabre/xamarin-forms-tab-badge#support--limitations

**Comment by xabre** [comment]
#53 will follow up
