### ISSUE TITLE
OnAppearing() of TabbedPage inside TabbedPage called when page is not clicked

### ISSUE THREAD

**Issue by Romain1Lambert** [xabre/xamarin-forms-tab-badge#54]
Hello, 
I am facing an issue with TabbedPage nested in TabbedPage.
Let's say have a TabbedPage named MasterTabbedPage.
I add many childs to it that are all ContentPages except one TabbedPage named TestPage (it is a regular and simply created tabbedPage).

`    

        public MasterTabbedPage()
        {
            InitializeComponent();
            Children?.Add(new PostsPage());
            Children?.Add(new ListingsPage());
            Children?.Add(new TestPage());
            Children?.Add(new NotificationsPage());
            Children?.Add(new MenuListPage());
            CurrentPage = null;
        }
`

The type of the class is : `public partial class MasterTabbedPage : Xamarin.Forms.TabbedPage`
When it loads, I have the PostPage displayed.

My issue is that all these pages have an OnAppearing() Method and Postpage one is called wich is normal but TestPage()'s one also and I did not click on it to display it.
Here is an example of OnAppearing for TestPage.

`
protected override void OnAppearing()
        {
            base.OnAppearing();
        }`

It is bothering me because let's say that when some data needs to be refreshed inside OnAppearing()
it will trigger these long operations once on load even when I did not reach the page.

I use the 2.0.0 latest stable version of the Nuget package.

**Comment by Romain1Lambert** [comment]
Thank you for the reply, I checked by commenting the ExportRenderer on my assembyInfo and it still occured, as you said it seems to be a Forms related behavior.

**Comment by toussam** [comment]
We created an issue into the Xamarin.Forms repository to notify the issue: https://github.com/xamarin/Xamarin.Forms/issues/4303
