### ISSUE TITLE
Use SetBadgeText?

### ISSUE THREAD

**Issue by kongdet** [xabre/xamarin-forms-tab-badge#57]
I have problems using SetBadgeText
It does not show me.
![1133](https://user-images.githubusercontent.com/44340399/47267638-f481c980-d570-11e8-92af-c0819cdf9fb6.jpg)

**Comment by xabre** [comment]
- SetBadgeText is overriden by your binding which might not have a proper binding context (check if it has a "Count" propery)
- either use a binding or SetBageText ...not both
