### ISSUE TITLE
Badge is drawn on the wrong tab

### ISSUE THREAD

**Issue by NPadrutt** [xabre/xamarin-forms-tab-badge#59]
I have a Tabbar with a bottom placement and two pages with a badge counter on them. When a push notification comes in the counter shall be increased for the activity tab. 

![screenshot_20181107-123801](https://user-images.githubusercontent.com/1764367/48130042-94d33000-e28b-11e8-8e75-682914961a5a.png)

Now is the counter set, but on the wrong tab as you can see above. Actually the birthday page doesn't have any counter at all and the counter is correctly removed when navigating away from the activity page.

That seems to be an issue with the new implementation to support the bottom placement. When I have it in the default placement it works as expected. 

![screenshot_20181107-124530](https://user-images.githubusercontent.com/1764367/48130094-c21fde00-e28b-11e8-9887-1bea3f72dfb3.png)

**Comment by xabre** [comment]
@NPadrutt can you reproduce this with the sample app? Or send a simple code sample which can reproduce this issue?

**Comment by xabre** [comment]
Closed because of age
