### ISSUE TITLE
[UAP] NuGet is missing payload files

### ISSUE THREAD

**Issue by michaelstonis** [xabre/xamarin-forms-tab-badge#61]
Using the version 2.1.0, the `HeaderTemplate.xbr` and `Plugin.Badge.UWP.xr.xml` files are both missing from the UAP release. The application cannot be compiled unless these files are available.

**Comment by mjspk** [comment]
same problem here any ideas

**Comment by Jamesmallon1** [comment]
Same issue also, did you guys manage to resolve the issue?

**Comment by mjspk** [comment]
no update still get this error i try to look for these files into the package itself but no success

**Comment by Jamesmallon1** [comment]
@mjspk are you using a BadgeTabbedPage custom renderer or are you just literally using the Nuget package?

**Comment by mjspk** [comment]
I'm using the Nuget package

**Comment by Jamesmallon1** [comment]
@xabre Is there anyway you could get onto this?

**Comment by Jamesmallon1** [comment]
@mjspk @michaelstonis 

Managed to produce the 2 files required from the source. I will attach them here. Just place both files in the relevant directory referenced by the error log 😄 

[Plugin.Badge.UWP.zip](https://github.com/xabre/xamarin-forms-tab-badge/files/2699323/Plugin.Badge.UWP.zip)

**Comment by Jamesmallon1** [comment]
@xabre can you include the files above in the nuget package and reupload?

**Comment by xabre** [comment]
Nuspec was updated in v2.1.1. Files should be there, please let me know if there are any other issues with the UWP package.
