### ISSUE TITLE
When I change the icon progmatically on selectetion of any tab badge got removed from iOS only please check the attachment 

### ISSUE THREAD

**Issue by aman720gupta** [xabre/xamarin-forms-tab-badge#65]
![screen shot 2019-02-27 at 5 10 58 pm](https://user-images.githubusercontent.com/47473789/53487859-b3676c00-3ab2-11e9-836e-c83e871f2045.png)
![screen shot 2019-02-27 at 5 11 07 pm](https://user-images.githubusercontent.com/47473789/53487860-b3676c00-3ab2-11e9-9914-c133430a733f.png)

**Comment by aman720gupta** [comment]
@xabre can you please help me with this

**Comment by xabre** [comment]
Fixed 2.1.2. Please reopen if still an issue
