### ISSUE TITLE
SetBadgeColor exception crash on iOS9.

### ISSUE THREAD

**Issue by allbdeveloper** [xabre/xamarin-forms-tab-badge#7]
Hi, 

It crash on iOS9(iPhone 5) if I use setbadgecolor. 
It's working fine on iOS10. (tested on iPhone 7)

I have a sample code that reproduce it.

Thanks.

**Comment by allbdeveloper** [comment]
[badgetest.zip](https://github.com/xabre/xamarin-forms-tab-badge/files/629864/badgetest.zip)

**Comment by allbdeveloper** [comment]
![screen shot 2016-12-05 at 7 08 05 am](https://cloud.githubusercontent.com/assets/14910356/20869657/5f9df104-baba-11e6-84dd-949cbcf318c3.png)

**Comment by allbdeveloper** [comment]
Plus, adding LinkerIncludeMe.cs does not make change.

**Comment by xabre** [comment]
It seems that setBadgeColor is only available starting from iOS 10.

**Comment by xabre** [comment]
Added check in 1.0.1. Should not crash anymore.

**Comment by allbdeveloper** [comment]
Thanks Adrian.
