### ISSUE TITLE
Badge not showing

### ISSUE THREAD

**Issue by stesvis** [xabre/xamarin-forms-tab-badge#71]
Hello,
I don't understand why the badge is not showing even with this simple example like this:

```
<?xml version="1.0" encoding="utf-8" ?>
<TabbedPage xmlns="http://xamarin.com/schemas/2014/forms"
            xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
            xmlns:prism="clr-namespace:Prism.Mvvm;assembly=Prism.Forms"
            prism:ViewModelLocator.AutowireViewModel="True"
            x:Class="VeloGuideApp.Views.HomeTabbedPage"
            Title="VeloGuide"
            xmlns:plugin="clr-namespace:Plugin.Badge.Abstractions;assembly=Plugin.Badge.Abstractions"
            SelectedTabIndex="{Binding SelectedTab}">

    <TabbedPage.Children>
        <ContentPage Title="Tab1" 
                 Icon="icontab1.png"
                 plugin:TabBadge.BadgeText="New" plugin:TabBadge.BadgeColor="Red">
            <StackLayout></StackLayout>
        </ContentPage>
    </TabbedPage.Children>

</TabbedPage>
```
Turns out to this:
![Screenshot_20190620_163426_com veloguide mobile prod](https://user-images.githubusercontent.com/6062684/59885684-50f3ed80-9379-11e9-88b2-1d8d97c82f56.jpg)

What could I be missing?

I did add this to the AssemblyInfo.cs too:
`[assembly: ExportRenderer(typeof(CustomTabbedPageRenderer), typeof(BadgedTabbedPageRenderer))]`

Where `CustomTabbedPageRenderer` is my custom tabbed page renderer.

Thanks for any help.

**Comment by stesvis** [comment]
UPDATE: the badge shows if I change it to this:
`[assembly: ExportRenderer(typeof(TabbedPage), typeof(BadgedTabbedPageRenderer))]`
But of course I lose my custom tabbed page customizations...
@xabre any idea? Thx!

**Comment by xabre** [comment]
@stesvis YOu have to inherit your own custom renderer from the 
BadgedTabbedPageRenderer and then register your custom renderer.

`public class CustomTabbedPageRenderer : BadgedTabbedPageRenderer`

`[assembly: ExportRenderer(typeof(TabbedPage), typeof(CustomTabbedPageRenderer))]`
