### ISSUE TITLE
38 "Skipping App1.Droid.Resource..." warnings when building Xamarin.Droid

### ISSUE THREAD

**Issue by nlhaney87** [xabre/xamarin-forms-tab-badge#72]
I created a new Mobile App (Xamarin.Forms) project in Visual Studio 2019 with the Master-Detail template.  I built the shared project and the android project after creating it, and it built with no warnings or errors.  I then installed Plugin.Badge 2.1.2 to the solution and again built the shared project and the android project,, but this time received 36 warnings from the android project (see attached screenshot).  Are these warnings are of any concern and can I fix them?
![Issue](https://user-images.githubusercontent.com/8601630/60534003-80362300-9cc6-11e9-8c27-c87013e782f8.PNG)

**Comment by xabre** [comment]
This is due to the different nuget package versions used by the plugin and your project, due to different XF versions (older for the badge). The next release will increase the minimum XF version to 4.0.0.425677 and should solve these warnings.

**Comment by xabre** [comment]
Should be fixed by v2.2.0. Give it a try and reopen if still an issue.

**Comment by nlhaney87** [comment]
Upgrading to 2.2.0 got rid of the warnings.  Thank you for the prompt response and fix.
