### ISSUE TITLE
Failed to resolve "Plugin.Badge.Abstractions.IBadge

### ISSUE THREAD

**Issue by uysuy** [xabre/xamarin-forms-tab-badge#73]
I have tried with this plugin but I got result as below
Failed to resolve "Plugin.Badge.Abstractions.IBadge" reference from "Plugin.Badge.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"	ProjectName.iOS

Please kindly help

Best Regards,
Uy Suy

**Comment by xabre** [comment]
There is no IBadge type. Without more info I cannot help.
