### ISSUE TITLE
Multiple properties with name BadgeView.Shared.CircleView.CornerRaius

### ISSUE THREAD

**Issue by nekszer** [xabre/xamarin-forms-tab-badge#76]
**Xamarin.Forms.Xaml.XamlParseException:** 'Position 8:81. Multiple properties with name 'BadgeView.Shared.CircleView.CornerRadius' found.'

Xamarin Forms: 4.2.0.709249

**Comment by xabre** [comment]
More info perhaps? ;) would be greatly appreciated. 
For example:

- Small code sample.
- Reproduction steps etc.
