### ISSUE TITLE
plugin:TabBadge.BadgeText <= 0 do not show badge?

### ISSUE THREAD

**Issue by LeoJHarris** [xabre/xamarin-forms-tab-badge#77]
Hi there, just wondering when Badge count is 0 would it be possible if we can optionally choose whether the badge is even shown? Rather then having the badge showing with the value 0

**Comment by xabre** [comment]
The badge content is a string (not interpreted as int). You can hide the badge by setting it to null.

**Comment by LeoJHarris** [comment]
Thanks, that helped.
