### ISSUE TITLE
Xamarin.Android Reload page

### ISSUE THREAD

**Issue by haiduong741** [xabre/xamarin-forms-tab-badge#82]
TabbedPage has 5 ContentPage, I stay at Current page 4 and click to page 3. It loading slow, sometime it crashed with alert Label Fast Renderer... 
It work well in iOS, but Android has this issue.

**Comment by xabre** [comment]
A clearer description with reproduction steps would help

**Comment by haiduong741** [comment]
Sorry. This issue belong Xamarin.Forms. I was post new Issue from here.
https://github.com/xamarin/Xamarin.Forms/issues/9880
