### ISSUE TITLE
Migration to AndroidX 

### ISSUE THREAD

**Issue by paleicikas** [xabre/xamarin-forms-tab-badge#87]
Are there plans to migrate the Xamarin.Android.* dependencies to Xamarin.AndroidX?
https://devblogs.microsoft.com/xamarin/androidx-nuget-packages-are-stable/

**Comment by xabre** [comment]
@paleicikas give 2.3.0-pre.2 a try.
https://www.nuget.org/packages/Plugin.Badge/2.3.0-pre.2

**Comment by paleicikas** [comment]
seems working, thanks

**Comment by TopSkillDeveloper** [comment]
When will the stable version be released?

**Comment by xabre** [comment]
Stable release 2.3.0
