### ISSUE TITLE
Binding no work

### ISSUE THREAD

**Issue by adilsonbatistajr** [xabre/xamarin-forms-tab-badge#93]
Is there any reason for this not to work:

<ContentPage Title="Sales" Icon="icon_bell.png" plugin:TabBadge.BadgeText="{Binding SalesCount}">

ViewModel:

 public string SalesCount
    {
        get
        {
            return _salesCount;
        }
        set
        {
            this.SetProperty(ref _salesCount, value);
        }
    }

Xamarin Forms 4.7, Plugin.Badge 2.2.1

**Comment by adilsonbatistajr** [comment]
Solution: plugin:TabBadge.BadgeText="{Binding Source={x:Reference tabParticipantes}, Path=BindingContext.ParticipantesCount}"

**Comment by LeoJHarris** [comment]
@adilsonbatistajr Found this answer for MAUI when migrating from Xamarin, oddly I didn't previously need the change suggested until now.
