### ISSUE TITLE
Error MSB3030: Could not copy the file "C:\Users\xxx\.nuget\packages\plugin.badge\2.3.0\lib\uap10.0\Plugin.Badge.UWP\Plugin.Badge.UWP.xr.xml" because it was not found.

### ISSUE THREAD

**Issue by anders9ustafsson** [xabre/xamarin-forms-tab-badge#94]
As the title says, in version 2.3.0 of *Plugin.Badge* on NuGet, the xr.xml file cannot be found when including *Plugin.Badge* in a UWP application.

Looking at the .nuget repository on the local system, it seems like the files in question now reside in a sub-directory *Plugin.Badge.UWP/Plugin.Badge.UWP* instead of, as in previous versions, *Plugin.Badge.UWP*.

![plugin-badge-issue](https://user-images.githubusercontent.com/6515030/89401968-69a69a80-d716-11ea-9b49-8712b03ba97e.png)

Error probably due to change in .nuspec file [here](https://github.com/xabre/xamarin-forms-tab-badge/commit/7d2107ad7578e6466cd37cd22e3ca04d2d48bf92#diff-427761474e2252cb4cb219f018d30517)?

**Comment by superbeller** [comment]
I have this problem too. How to fix it?

**Comment by BenReierson** [comment]
Same issue. The files are one level too deep. Need to be moved up.

**Comment by mhrastegary77** [comment]
Same issue

**Comment by ManuLin** [comment]
I am facing the same issue.
